---
title: "Dissertation"
output: html_document
date: "2025-09-23"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#libraries
```{r}
set.seed(123)
library(grid)
library(viridisLite)
library(tidyverse)
library(Matrix)
library(MASS)
library(BB)
library(xtable)
library(plotly)
library(minpack.lm)
library(htmlwidgets)
library(reticulate)
sink.number()
```




#how variance affects time series
```{r}
set.seed(123)
pos_ar_df = tibble(power = seq(-5,5, by = 1) %>% rep(each = 9), ma = seq(-.8,.8, by = .2) %>% rep(times = 11)) %>%
  mutate(variance = 2 ^ power) %>%
  rowwise() %>%
  mutate(ma_b = fwd(.4, ma, 1, variance, 1)[1])
pos_ar_df$ma = as.factor(pos_ar_df$ma)

ggplot(data = pos_ar_df) +
  geom_line(mapping = aes(x = power, y = ma_b, group = ma, col = ma)) +
    scale_x_continuous(breaks = seq(-5,5, by = 1)) +
  scale_y_continuous(breaks = seq(-1,1, by = 0.2)) +
  xlab("Variance of added noise (log base two)") +
  ylab("New moving average parameter") +
  ggtitle("")+
   labs(color = expression(theta)) +
  scale_color_manual(values = c(
  "#000000", # black
  "#E69F00", # orange
  "#56B4E9", # sky blue
  "#009E73", # bluish green
  "#F0E442", # yellow
  "#0072B2", # blue
  "#D55E00", # vermillion
  "#CC79A7", # reddish purple
  "#999999"  # grey (extension)
)) +
  theme(
  axis.title.x = element_text(size = 16),
  axis.title.y = element_text(size = 16),
  legend.title = element_text(size = 14),
  legend.text  = element_text(size = 12),
  legend.key.size = unit(1.2, "lines")
  )

ggsave("../output/paper/figures/pos_ar_var_effect.pdf", height = 6, width = 8)

neg_ar_df = tibble(power = seq(-5,5, by = 1) %>% rep(each = 9), ma = seq(-.8,.8, by = .2) %>% rep(times = 11)) %>%
  mutate(variance = 2 ^ power) %>%
  rowwise() %>%
  mutate(ma_b = fwd(-.4, ma, 1, variance, 1)[1])
neg_ar_df$ma = as.factor(neg_ar_df$ma)

ggplot(data = neg_ar_df) +
  geom_line(aes(x = power, y = ma_b, group = ma, col = ma)) +
    scale_x_continuous(breaks = seq(-5,5, by = 1)) +
  scale_y_continuous(breaks = seq(-1,1, by = 0.2)) +
  xlab("Variance of added noise (log base two)") +
  ylab("New moving average parameter") +
  labs(color = expression(theta)) +
  scale_color_manual(values = c(
  "#000000", # black
  "#E69F00", # orange
  "#56B4E9", # sky blue
  "#009E73", # bluish green
  "#F0E442", # yellow
  "#0072B2", # blue
  "#D55E00", # vermillion
  "#CC79A7", # reddish purple
  "#999999"  # grey (extension)
))
  theme(
  axis.title.x = element_text(size = 16),
  axis.title.y = element_text(size = 16),
  legend.title = element_text(size = 14),
  legend.text  = element_text(size = 12),
  legend.key.size = unit(1.2, "lines")
)

ggsave("../output/paper/figures/neg_ar_var_effect.pdf", height = 6, width = 8)
no_ar_df = tibble(power = seq(-5,5, by = 1) %>% rep(each = 9), ma = seq(-.8,.8, by = .2) %>% rep(times = 11)) %>%
  mutate(variance = 2 ^ power) %>%
  rowwise() %>%
  mutate(ma_b = fwd(0, ma, 1, variance, 1)[1])

no_ar_df$ma = as.factor(no_ar_df$ma)

ggplot(data = no_ar_df) +
  geom_line(mapping = aes(x = power, y = ma_b, group = ma, col = ma)) +
    # Force gridlines at your desired values
  scale_x_continuous(breaks = seq(-5,5, by = 1)) +
  scale_y_continuous(breaks = seq(-1,1, by = 0.2)) +
  xlab("Variance of added noise (log base two)") +
  ylab("New moving average parameter") +
   labs(color = expression(theta)) +
  scale_color_manual(values = c(
  "#000000", # black
  "#E69F00", # orange
  "#56B4E9", # sky blue
  "#009E73", # bluish green
  "#F0E442", # yellow
  "#0072B2", # blue
  "#D55E00", # vermillion
  "#CC79A7", # reddish purple
  "#999999"  # grey (extension)
))
  theme(
  axis.title.x = element_text(size = 16),
  axis.title.y = element_text(size = 16),
  legend.title = element_text(size = 14),
  legend.text  = element_text(size = 12),
  legend.key.size = unit(1.2, "lines")
  )

ggsave("../output/paper/figures/no_ar_var_effect.pdf", height = 6, width = 8)
```

#Showing bias introduced in Modugno of fitting ARMA-Process with AR(1)
##Estimating phi
```{r}
#Params
ar_bias_vara = 2
veta_arbias = 1
minutes = .4
T_arbias = 1000


```


```{r}
set.seed(123)


ar_bias_df = tibble(phi = rep(seq(-.9, .9, by = .2), each = 5), var_a = rep(c(1/4,1/2,1,2,4), times = 10)) |>
  mutate(log2 = log(var_a, base = 2))
start = Sys.time()
ar_bias_df = ar_bias_df %>%
  rowwise() %>%
  mutate(means = emp_exp_ar_vs_arma(phi, var_a, TT = T_arbias, sims = 1) %>% list())
end = Sys.time()
single_sim = as.numeric(end - start, units = "mins")
sims_arbias = max((minutes %/% single_sim),1)
ar_bias_df = ar_bias_df %>%
  rowwise() %>%
  mutate(means = emp_exp_ar_vs_arma(phi, var_a, TT = T_arbias, sims = sims_arbias) %>% list())

ar_bias_df <- ar_bias_df %>%
  ungroup() %>%                 # important after rowwise()
  unnest_wider(means)

ar_bias_df = ar_bias_df %>%
  rowwise() %>%
  mutate(true_var = fwd(ar = phi, ma = 0, veta = veta_arbias, veps = var_a, n = 1)[2]) %>%
  ungroup()
```



```{r}
set.seed(123)

# ---- 1. Long-format points (3 per row) ----
df_long <- ar_bias_df %>%
  mutate(
    true_phi = phi,
    row_id = row_number()
  ) %>%
  pivot_longer(
    cols = c(phi, phi_mean_ar, phi_mean_arma),
    names_to = "source",
    values_to = "z"
  )


ggplot(data = df_long |> filter(var_a == 2)) + 
  geom_point(mapping = aes(x = true_phi, y = z, colour = source),
             size = 5) +
  scale_color_discrete(
    labels = c(phi = "True Value of Phi",
               phi_mean_ar = "Mean Estimate Fitting AR(1)",
               phi_mean_arma = "Mean Estimate Fitting ARMA(1,1)"),
    name = NULL
  ) + 
  xlab("True Value of Phi") + 
  ylab("Parameter and Estimate Values") +
  theme(
    axis.title.x = element_text(size = 20),
    axis.title.y = element_text(size = 20),
    legend.text = element_text(size = 15)
  )
ggsave("../output/paper/figures/ar_bias.pdf", width = 12, height = 6)

# ---- 2. Build vertical line segments with NA breaks ----
segments_df <- df_long %>%
  filter(source != "phi") %>%
  transmute(
    row_id,
    source,
    x1 = true_phi,
    y1 = log2,
    z1 = z,
    x2 = true_phi,
    y2 = log2,
    z2 = true_phi
  ) %>%
  rowwise() %>%
  summarise(
    x = list(c(x1, x2, NA)),
    y = list(c(y1, y2, NA)),
    z = list(c(z1, z2, NA)),
    source = source,
    .groups = "drop"
  ) %>%
  unnest(c(x, y, z))

# ---- 3. Plot ----
p = plot_ly() %>%
  # Points
  add_markers(
    data = df_long,
    x = ~true_phi,
    y = ~log2,
    z = ~z,
    color = ~source,
    colors = c(
      phi = "blue",
      phi_mean_ar = "red",
      phi_mean_arma = "green4"
    ),
    marker = list(size = 5)
  ) %>%
  
  # Vertical connecting segments
  add_trace(
    data = segments_df,
    x = ~x,
    y = ~y,
    z = ~z,
    color = ~source,
    colors = c(
      phi_mean_ar = "red",
      phi_mean_arma = "green4"
    ),
    type = "scatter3d",
    mode = "lines",
    line = list(width = 3),
    opacity = 0.6,
    showlegend = FALSE
  ) %>%
  
  layout(
    scene = list(
      xaxis = list(
        title = "φ (true)",
        range = c(-1, 1)
      ),
      yaxis = list(
        title = "log₂ var ratio",
        range = c(-5, 5)
      ),
      zaxis = list(title = "value"),
      aspectmode = "manual",
      aspectratio = list(x = 1, y = 2.5, z = 1),
      camera = list(eye = list(x = 1.5, y = 1.5, z = 1.2))
    ),
    legend = list(title = list(text = "Source"))
  )
p
htmlwidgets::saveWidget(
  p,
  file = "../output/paper/figures/phi_3d_plot.html",
  selfcontained = TRUE
)
```

```{r}
#Params

cov_conf = 0
sims = 1
TT = 1000
ll = 5
phi = .9
theta = 0
var_eps = 20
var_eta = 1
b_0 = 43
b_t = -.001
b_1 = .25
beta = c(b_0,b_t, b_1)
minutes = .4
```

```{r}
set.seed(123)
n_t = rpois(n = TT, lambda = ll) + 1
NN = sum(n_t)

eps = rnorm(n = NN, mean = 0, sd = sqrt(var_eps))
df = tibble(t = rep(1:TT, times = n_t), eps = eps)


i_x = rbinom(n = NN, size = 1, prob = .5)
X_f = cbind(1, df$t, i_x)
colnames(X_f) = c("intercept", "t", "x")
df$x = i_x
ts = arima.sim(model = list(ar = phi, ma = theta), n = TT, sd = sqrt(var_eta))
df$ts = rep(ts, times = n_t)
df$y = X_f %*% beta + df$ts + df$eps
df$y = as.vector(df$y)

ggplot() + 
  geom_point(data = df %>% filter(x == 1), mapping = aes(x = t, y = y), col = "green") +
  geom_point(data = df %>% filter(x == 0), mapping = aes(x = t, y = y), col = "blue")+
  xlab("Time") + 
  ylab("Value")+
  theme(
    axis.title.x = element_text(size = 16),
    axis.title.y = element_text(size = 16)
  )
ggsave("../output/paper/figures/are.png", width = 8, height = 6)
#current chunk

estimates = c()
zscores = c()
variances = c()

estimates_remarcs = c()
zscores_remarcs = c()
veta_remarcs = c()
veps_remarcs = c()

start = Sys.time()
n_t = rpois(n = TT, lambda = ll) + 1
X_t = f_Xt_sparse(n_t)



fwd_est = fwd(phi, theta, var_eta, var_eps, (mean(n_t[n_t != 0]^(-1)))^(-1))
theta_b = fwd_est[1]
var_b = fwd_est[2]
var_a = var_eps * mean(n_t[n_t != 0]^(-1))

X_f = tibble(intercept = 1, day = as.vector(X_t %*% (1:TT)), x = rbinom(n = sum(n_t), size = 1, prob = .5))
var_eps = var_eps
ar = phi 
ma = theta 
veta = var_eta
test = sim_arman_reg(n_t, 
                     beta, 
                     X_f , 
                     var_eps , 
                     ar , 
                     ma , 
                     veta )


linmod = lm(data = test, formula = "y ~ 1 + t + x")

rmarcs = RCSfixed.fit(mod = linmod, dat = test, resp_var = "y")



df_armacov = test %>%
  group_by(t) %>%
  summarize( n = n(), x = mean(x), y = mean(y))

covariate_matrix = matrix(0, nrow = nrow(df_armacov), ncol = 3)
covariate_matrix[,1] = 1
covariate_matrix[,2] = df_armacov$t
covariate_matrix[,3] = df_armacov$x

armacov = arima(df_armacov$y, order = c(1,0,1), xreg = covariate_matrix[,2:3], include.mean = TRUE, method = "ML")

sim_est = armacov$coef
sim_se = armacov$var.coef %>% diag() %>% sqrt()
sim_z = sim_est / sim_se
zscores = cbind(zscores, sim_z)
estimates = cbind(estimates, armacov$coef)
variance = armacov$sigma2
variances = append(variances, variance)

sim_est_remarcs = c(rmarcs$TS_Pars[,1],rmarcs$Beta_Pars[,1])
sim_se_remarcs = c(rmarcs$TS_Pars[,2], rmarcs$Beta_Pars[,2])
sim_z_remarcs = sim_est_remarcs / sim_se_remarcs
zscores_remarcs = cbind(zscores_remarcs, sim_z_remarcs)
estimates_remarcs = cbind(estimates_remarcs, sim_est_remarcs)
veta_remarcs = cbind(rmarcs$`TS Variance`)
veps_remarcs = cbind(rmarcs$`Individual Variance`)
end = Sys.time()
single_sim = as.numeric(end - start, units = "mins")
sims = max((minutes %/% single_sim),1)

for (sim in 1:(sims - 1)){
n_t = rpois(n = TT, lambda = ll) + 1
X_t = f_Xt_sparse(n_t)



fwd_est = fwd(phi, theta, var_eta, var_eps, (mean(n_t[n_t != 0]^(-1)))^(-1))
theta_b = fwd_est[1]
var_b = fwd_est[2]
var_a = var_eps * mean(n_t[n_t != 0]^(-1))

X_f = tibble(intercept = 1, day = as.vector(X_t %*% (1:TT)), x = rbinom(n = sum(n_t), size = 1, prob = .5))
var_eps = var_eps
ar = phi 
ma = theta 
veta = var_eta
test = sim_arman_reg(n_t, 
                     beta, 
                     X_f , 
                     var_eps , 
                     ar , 
                     ma , 
                     veta )


linmod = lm(data = test, formula = "y ~ 1 + t + x")

rmarcs = RCSfixed.fit(mod = linmod, dat = test, resp_var = "y")



df_armacov = test %>%
  group_by(t) %>%
  summarize( n = n(), x = mean(x), y = mean(y))

covariate_matrix = matrix(0, nrow = nrow(df_armacov), ncol = 3)
covariate_matrix[,1] = 1
covariate_matrix[,2] = df_armacov$t
covariate_matrix[,3] = df_armacov$x

armacov = arima(df_armacov$y, order = c(1,0,1), xreg = covariate_matrix[,2:3], include.mean = TRUE, method = "ML")

sim_est = armacov$coef
sim_se = armacov$var.coef %>% diag() %>% sqrt()
sim_z = sim_est / sim_se
zscores = cbind(zscores, sim_z)
estimates = cbind(estimates, armacov$coef)
variance = armacov$sigma2
variances = append(variances, variance)

sim_est_remarcs = c(rmarcs$TS_Pars[,1],rmarcs$Beta_Pars[,1])
sim_se_remarcs = c(rmarcs$TS_Pars[,2], rmarcs$Beta_Pars[,2])
sim_z_remarcs = sim_est_remarcs / sim_se_remarcs
zscores_remarcs = cbind(zscores_remarcs, sim_z_remarcs)
estimates_remarcs = cbind(estimates_remarcs, sim_est_remarcs)
veta_remarcs = cbind(rmarcs$`TS Variance`)
veps_remarcs = cbind(rmarcs$`Individual Variance`)

}

# rowMeans(estimates)
# hist(variances)
# rowMeans(2 * (1 - pnorm(abs(zscores))) < .05)

ts_cov_df = tibble(Parameter = c("phi", 
                            "theta", 
                            "Intercept", 
                            "Slope",
                            "Covariate"),
                   `True Value` = c(phi, theta, beta[1], beta[2], beta[3]),
                   `TSCOV Mean` = rowMeans(estimates), 
                   `REMARCS Mean` = rowMeans(estimates_remarcs),
                   `Sig. Freq. TS` = rowMeans(2 * (1 - pnorm(abs(zscores))) < .05),
                   `Sig. Freq. REMARCS` = rowMeans(2 * (1 - pnorm(abs(zscores_remarcs))) < .05)
)


print(xtable(ts_cov_df, digits = c(0, 3, 3, 3, 3,3,3)), include.rownames = FALSE, file = "../output/paper/figures/arma_cov_df.txt")

print(xtable(head(test %>% dplyr::select(t,x,y))), include.rownames = FALSE, file = "../output/paper/figures/arma_cov_head.txt")

print(xtable(head(df_armacov)), include.rownames = FALSE, file = "../output/paper/figures/arma_cov_head_daily.txt")

cov_conf = ts_cov_df$`Sig. Freq. TS`[ts_cov_df$Parameter == "Covariate"] %>% as.numeric() * 100

```

#grid of empirical confidence region efficacy
```{r}
#Params

tol = .05
arman_veta = 1
arman_veps = 1
arman_lambda = 5

arman_T1 = 1000
arman_T2 = 5000
arman_alpha = .05
minutes = .4
```

```{r}
set.seed(123)
conf_df = tibble(ar = rep(seq(-.9,.9,by = .4), each = 5),
                 ma = rep(seq(0,.8,by = .2), times = 5)
                 )
start = Sys.time()

conf_df = mutate(rowwise(conf_df),
                 e_conf_l_3_2 = ifelse(abs(ar + ma) < tol,
                                       NA,
                                       emp_conf_l(phi = ar,
                                                  theta = ma,
                                                  var_eta = arman_veta,
                                                  TT = arman_T1,
                                                  sims = 1,
                                                  var_eps = arman_veps,
                                                  lambda = arman_lambda,
                                                  alpha = arman_alpha
                                                  )
                                       )
                 )
end = Sys.time()
single_sim = as.numeric(end - start, units = "mins")
arman_sims = max(minutes %/% single_sim, 1)

conf_df = mutate(rowwise(conf_df),
                 e_conf_l_4_2 = ifelse(abs(ar + ma) < tol,
                                       NA,
                                       emp_conf_l(phi = ar,
                                                  theta = ma,
                                                  var_eta = arman_veta,
                                                  TT = arman_T2,
                                                  sims = arman_sims,
                                                  var_eps = arman_veps,
                                                  lambda = arman_lambda,
                                                  alpha = arman_alpha
                                                  )
                                       )
                 )

end = Sys.time()
print(end-start)


ggplot(conf_df, aes(x = factor(ar), y = factor(ma), fill = e_conf_l_3_2)) +
  geom_tile() +
    labs(fill = "Empirical Confidence") +
  xlab("AR Parameter") +
  ylab("MA Parameter") +
   scale_fill_viridis_c(limits = c(min(conf_df$e_conf_l_3_2), 1)) +
  theme(
    axis.title.x = element_text(size = 16),
    axis.title.y = element_text(size = 16)
  )

ggsave("../output/paper/figures/e_conf_l_3_2.pdf", width = 7, height = 7)

ggplot(conf_df, aes(x = factor(ar), y = factor(ma), fill = e_conf_l_4_2)) +
  geom_tile() +
    labs(fill = "Empirical Confidence") +
  xlab("AR Parameter") +
  ylab("MA Parameter") +
   scale_fill_viridis_c(limits = c(min(conf_df$e_conf_l_4_2), 1)) +
  theme(
    axis.title.x = element_text(size = 16),
    axis.title.y = element_text(size = 16)
  )

ggsave("../output/paper/figures/e_conf_l_4_2.pdf", width = 7, height = 7)

```

```{r}
#Params

phi_vec = rep(seq(.1,.9, by = .4), each = 3)
theta_vec = rep(seq(0,.8, by = .4), times = 3)
fearma_sim_df = tibble(phi = phi_vec, theta = theta_vec)

fearma_T = 1000
fearma_sims = 2
fearma_veta = var_eta
fearma_veps = var_eps
fearma_int = b_0
fearma_slope = b_t
fearma_x = b_1
fearma_beta = c(fearma_int,
                fearma_slope,
                fearma_x)
fearma_alpha = .05
```


```{r}

set.seed(123)
fearma_sim_df2 = mutate(rowwise(fearma_sim_df), 
                        emp_conf = arman_gls_em(sims = fearma_sims, 
                                                TT = fearma_T, 
                                                ar = phi, 
                                                ma = theta, 
                                                veta = fearma_veta, 
                                                veps = fearma_veps, 
                                                beta = fearma_beta
                                                ) %>% list())

fearma_sim_df2$l1_conf = sapply(fearma_sim_df2$emp_conf, function(x) x[[1]])

fearma_sim_df2$l2_conf = sapply(fearma_sim_df2$emp_conf, function(x) x[[2]])

```

```{r}

ggplot(fearma_sim_df2, aes(x = factor(phi), y = factor(theta), fill = l1_conf)) +
  geom_tile() +
  xlab("AR Parameter") + 
  ylab("MA Parameter") + 
  scale_fill_viridis_c() +
    labs(fill = "Empirical Confidence") +
  theme(
    axis.title.x = element_text(size = 16),
    axis.title.y = element_text(size = 16)
  )
  
ggsave("../output/paper/figures/l1_conf.pdf", width = 7, height = 7)

ggplot(fearma_sim_df2, aes(x = factor(phi), y = factor(theta), fill = l2_conf)) +
  geom_tile() +
  xlab("AR Parameter") + 
  ylab("MA Parameter") +
  scale_fill_viridis_c() +
    labs(fill = "Empirical Confidence") +
  theme(
    axis.title.x = element_text(size = 16),
    axis.title.y = element_text(size = 16)
  )
  
ggsave("../output/paper/figures/l2_conf.pdf", width = 7, height = 7)

l1_mat <- fearma_sim_df2 %>%
  select(phi, theta, l1_conf) %>%
  pivot_wider(names_from = theta, values_from = l1_conf) %>%
  arrange(phi)

l2_mat <- fearma_sim_df2 %>%
  select(phi, theta, l2_conf) %>%
  pivot_wider(names_from = theta, values_from = l2_conf) %>%
  arrange(phi)

l1_df <- as.data.frame(l1_mat)
l2_df <- as.data.frame(l2_mat)

l1_tab <- xtable(
  l1_df,
  caption = "Empirical confidence levels for varying time series parameters",
  label = "tab:l1_conf"
)

print(l1_tab,
      file = "../output/paper/figures/fearma_l1_conf.txt",
      include.rownames = FALSE,
      caption.placement = "top")

l2_tab <- xtable(
  l2_df,
  caption = "Empirical confidence levels for varying time series parameters",
  label = "tab:l2_conf"
)
print(l2_tab,
      file = "../output/paper/figures/fearma_l2_conf.txt",
      include.rownames = FALSE,
      caption.placement = "top")
```

```{r}
#Params

are_T = 1000
are_veta = var_eta
are_veps = 20
are_int = b_0
are_slope = b_t
are_cov = b_1
are_beta = c(are_int, are_slope, are_cov)
are_repel = tibble(phi = seq(.1,.9, by = .2))
minutes = .4
```

```{r}
set.seed(123)
start = Sys.time()
are_repel = are_repel |>
  rowwise() |>
  mutate(are_mean = list(are_stability(sims = 1,
                                       TT = are_T,
                                       ar = phi,
                                       ma = 0,
                                       veta = are_veta,
                                       veps = are_veps,
                                       beta = are_beta,
                                       lambda_n = 5
              )
              ))
end = Sys.time()
single_sim = as.numeric(end - start, units = "mins")
are_sims = max(minutes %/% single_sim, 1)
are_repel = are_repel |>
  rowwise() |>
  mutate(are_mean = list(are_stability(sims = are_sims,
                                       TT = are_T,
                                       ar = phi,
                                       ma = 0,
                                       veta = are_veta,
                                       veps = are_veps,
                                       beta = are_beta,
                                       lambda_n = 5
              )
              ))
are_repel$phi_mean = sapply(are_repel$are_mean, function(x) x[[1]])
are_repel$phi_captured = sapply(are_repel$are_mean, function(x) x[[2]])

are_repel$veta_mean = sapply(are_repel$are_mean, function(x) x[[3]])

are_tab = are_repel |> dplyr::select(phi, phi_mean, phi_captured) |> as.matrix()
are_tab = t(are_tab)
are_tab <- xtable(
  are_tab,
  caption = "Aggregate Estimates and Empirical Confidence Levels for AR parameter Following Ideal Time Series Estimation",
  label = "tab:are_stability"
)

print(are_tab,
      file = "../output/paper/figures/are_tab.txt",
      include.rownames = TRUE,
      include.colnames = FALSE,
      caption.placement = "top")
```

#Model Selection: u is AR(1)

```{r}
#params
uar_T = 1000
#uar_sims = 1
uar_veta = var_eta
uar_veps = 20
uar_int = b_0
uar_slope = b_t
uar_cov = b_1
uar_beta = c(are_int, are_slope, are_cov)
uar_df = tibble(phi = seq(-.9,.9, by = .4))
uar_lambda = 5
minutes = .4
```

```{r}
set.seed(123)
start = Sys.time()
uar_df = uar_df |>
  rowwise() |>
  mutate(results = (arman_gls_ms(sims = 1,
                                       TT = uar_T,
                                       ar = phi,
                                       ma = 0,
                                       veta = uar_veta,
                                       veps = uar_veps,
                                       beta = uar_beta,
                                       lambda_n = uar_lambda
              ) |> list()
              ))
end = Sys.time()
single_sim = as.numeric(end - start, units = "mins")
uar_sims = max(1, minutes %/% single_sim)
uar_df = uar_df |>
  rowwise() |>
  mutate(results = (arman_gls_ms(sims = uar_sims,
                                       TT = uar_T,
                                       ar = phi,
                                       ma = 0,
                                       veta = uar_veta,
                                       veps = uar_veps,
                                       beta = uar_beta,
                                       lambda_n = uar_lambda
              ) |> list()
              ))

uar_df$theta_captured = sapply(uar_df$results, function(x) x[[1]])
uar_df = uar_df |>
  dplyr::select(phi, theta_captured)
uar_tab = uar_df |> as.matrix()
uar_tab = t(uar_tab)
uar_tab <- xtable(
  uar_tab,
  caption = "Rates at which MA Parameter is Insignificant When True Parameter is Zero",
  label = "tab:uar_theta_insig"
)

print(uar_tab,
      file = "../output/paper/figures/uar_tab.txt",
      include.rownames = TRUE,
      include.colnames = FALSE,
      caption.placement = "top")
```

#Model Selection: u is MA(1)

```{r}
#params
uma_T = 1000
# uma_sims = 1 #Deprecated since sims is now determined by minutes
uma_veta = var_eta
uma_veps = 20
uma_int = b_0
uma_slope = b_t
uma_cov = b_1
uma_beta = c(are_int, are_slope, are_cov)
uma_df = tibble(theta = seq(-.9,.9, by = .4))
uma_lambda = 5
minutes = .4
```

```{r}
set.seed(123)
start = Sys.time()
uma_df = uma_df |>
  rowwise() |>
  mutate(results = (arman_gls_ms(sims = 1,
                                       TT = uma_T,
                                       ar = 0,
                                       ma = theta,
                                       veta = uma_veta,
                                       veps = uma_veps,
                                       beta = uma_beta,
                                       lambda_n = uma_lambda
              ) |> list()
              ))
end = Sys.time()
single_sim = as.numeric(end - start, units = "mins")
uma_sims = max(1, minutes %/% single_sim)
uma_df = uma_df |>
  rowwise() |>
  mutate(results = (arman_gls_ms(sims = uma_sims,
                                       TT = uma_T,
                                       ar = 0,
                                       ma = theta,
                                       veta = uma_veta,
                                       veps = uma_veps,
                                       beta = uma_beta,
                                       lambda_n = uma_lambda
              ) |> list()
              ))

uma_df$phi_captured = sapply(uma_df$results, function(x) x[[2]])
uma_df = uma_df |>
  dplyr::select(theta, phi_captured)
uma_tab = uma_df |> as.matrix()
uma_tab = t(uma_tab)
uma_tab <- xtable(
  uma_tab,
  caption = "Rates at which AR Parameter is Insignificant When True Parameter is Zero",
  label = "tab:uma_phi_insig"
)

print(uma_tab,
      file = "../output/paper/figures/uma_tab.txt",
      include.rownames = TRUE,
      include.colnames = FALSE,
      caption.placement = "top")
```



```{r}
sink("../output/paper/r_variables.tex")
cat(sprintf("\\newcommand{\\intrcpt}{%s}\n", b_0))
cat(sprintf("\\newcommand{\\slope}{%s}\n", b_t))
cat(sprintf("\\newcommand{\\covind}{%s}\n", b_1))
cat(sprintf("\\newcommand{\\ar}{%s}\n", phi))
cat(sprintf("\\newcommand{\\ma}{%s}\n", theta))
cat(sprintf("\\newcommand{\\vareps}{%s}\n", var_eps))
cat(sprintf("\\newcommand{\\vareta}{%s}\n", var_eta))
cat(sprintf("\\newcommand{\\sims}{%s}\n", sims))
cat(sprintf("\\newcommand{\\covconf}{%s}\n", cov_conf))
cat(sprintf("\\newcommand{\\armanconfveps}{%s}\n", arman_veps))
cat(sprintf("\\newcommand{\\armanconfveta}{%s}\n", arman_veta))
cat(sprintf("\\newcommand{\\armanconflambda}{%s}\n", arman_lambda))
cat(sprintf("\\newcommand{\\armanconfsims}{%s}\n", arman_sims))
cat(sprintf("\\newcommand{\\armanconfTleft}{%s}\n", arman_T1))
cat(sprintf("\\newcommand{\\armanconfTright}{%s}\n", arman_T2))
cat(sprintf("\\newcommand{\\armanconfalpha}{%s}\n", arman_alpha))
cat(sprintf("\\newcommand{\\arbiasveta}{%s}\n", veta_arbias))
cat(sprintf("\\newcommand{\\arbiassims}{%s}\n", sims_arbias))
cat(sprintf("\\newcommand{\\arbiasT}{%s}\n", T_arbias))
cat(sprintf("\\newcommand{\\arbiasvara}{%s}\n", ar_bias_vara))
cat(sprintf("\\newcommand{\\Tfearma}{%s}\n", fearma_T))
cat(sprintf("\\newcommand{\\simsfearma}{%s}\n", fearma_sims))
cat(sprintf("\\newcommand{\\vetafearma}{%s}\n", fearma_veta))
cat(sprintf("\\newcommand{\\vepsfearma}{%s}\n", fearma_veps))
cat(sprintf("\\newcommand{\\intfearma}{%s}\n", fearma_int))
cat(sprintf("\\newcommand{\\slopefearma}{%s}\n", fearma_slope))
cat(sprintf("\\newcommand{\\xfearma}{%s}\n", fearma_x))
cat(sprintf("\\newcommand{\\alphafearma}{%s}\n", fearma_alpha))
cat(sprintf("\\newcommand{\\tol}{%s}\n", tol))
cat(sprintf("\\newcommand{\\areT}{%s}\n", are_T))
cat(sprintf("\\newcommand{\\aresims}{%s}\n", are_sims))
cat(sprintf("\\newcommand{\\areveta}{%s}\n", are_veta))
cat(sprintf("\\newcommand{\\areveps}{%s}\n", are_veps))
cat(sprintf("\\newcommand{\\areslope}{%s}\n", are_slope))
cat(sprintf("\\newcommand{\\areint}{%s}\n", are_int))
cat(sprintf("\\newcommand{\\arecov}{%s}\n", are_cov))
cat(sprintf("\\newcommand{\\umaT}{%s}\n", uma_T))
cat(sprintf("\\newcommand{\\umasims}{%s}\n", uma_sims))
cat(sprintf("\\newcommand{\\umaveta}{%s}\n", uma_veta))
cat(sprintf("\\newcommand{\\umaveps}{%s}\n", uma_veps))
cat(sprintf("\\newcommand{\\umaslope}{%s}\n", uma_slope))
cat(sprintf("\\newcommand{\\umaint}{%s}\n", uma_int))
cat(sprintf("\\newcommand{\\umacov}{%s}\n", uma_cov))
cat(sprintf("\\newcommand{\\umalambda}{%s}\n", uma_lambda))
cat(sprintf("\\newcommand{\\uarT}{%s}\n", uar_T))
cat(sprintf("\\newcommand{\\uarsims}{%s}\n", uar_sims))
cat(sprintf("\\newcommand{\\uarveta}{%s}\n", uar_veta))
cat(sprintf("\\newcommand{\\uarveps}{%s}\n", uar_veps))
cat(sprintf("\\newcommand{\\uarslope}{%s}\n", uar_slope))
cat(sprintf("\\newcommand{\\uarint}{%s}\n", uar_int))
cat(sprintf("\\newcommand{\\uarcov}{%s}\n", uar_cov))
cat(sprintf("\\newcommand{\\uarlambda}{%s}\n", uar_lambda))
sink()
sink.number()
```
